# Generated by Django 4.2.15 on 2024-08-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Likes',
        ),
    ]
